### ISSUE TITLE
Xhamster has stopped working, 

### ISSUE THREAD

**Issue by chronic0383** [Athlon1600/php-proxy-plugin-bundle#10]
Hi buddy, sorry to post up again.
It seems the xhamster plugin has stopped working, the page doesn't seem to load correctly. Don't know if this is just me

**Comment by Athlon1600** [comment]
Fixed:  
https://github.com/Athlon1600/php-proxy-plugin-bundle/commit/c6d69b7bd8ba431680cd22213f2cce6c48c42a9f

**Comment by chronic0383** [comment]
Thanks buddy, you are a star. 😁
