### ISSUE TITLE
How to use these plugins?

### ISSUE THREAD

**Issue by kinglyl** [Athlon1600/php-proxy-plugin-bundle#14]
I download these plugins like `YoutubePlugin.php` and put it in the `/plugins` folder, but my site down right away.
Can you tell me how to use it, I can not use composer.

**Comment by Athlon1600** [comment]
Youtube is enabled by default actually. To enable/disable a particular plugin, go to your app's config.php and add the name of the file (without .php) to the `$plugins` array here:  
https://github.com/Athlon1600/php-proxy-app/blob/master/config.php#L23

**Comment by kinglyl** [comment]
so I should put these things into the `/vendor/athlon1600/php-proxy/src/Plugin/` folder ?
I used to put plugins in the `plugins` folder

**Comment by kinglyl** [comment]
Please reply me ^O^

**Comment by Athlon1600** [comment]
this whole package is installed by default when using php-proxy-app:  
https://github.com/Athlon1600/php-proxy-app/blob/master/composer.json#L10  
  
and all of these plugins are enabled by default too:
https://github.com/Athlon1600/php-proxy-app/blob/master/config.php#L23  
  
so I don't think you have to do anything from your end. it's all already setup.

**Comment by kinglyl** [comment]
Thanks!
