### ISSUE TITLE
When Adding YouTube Plugin the whole thing breaks

### ISSUE THREAD

**Issue by MapGuy11** [Athlon1600/php-proxy-plugin-bundle#17]
Kinda confused how to add the plugins I added YouTube-Plugin and it broke the whole install

**Comment by MapGuy11** [comment]
no respond I close

**Comment by Baggette** [comment]
> Kinda confused how to add the plugins I added YouTube-Plugin and it broke the whole install

did you ever figure this out? I am having the same issue.
