### ISSUE TITLE
New YouTube layout

### ISSUE THREAD

**Issue by BinBashBanana** [Athlon1600/php-proxy-plugin-bundle#18]
Hi there, I'm wondering how I would enable the new youtube look.

It looks like I could change something in YoutubePlugin.php:
```
    // force old YouTube layout!
    public function onBeforeRequest(ProxyEvent $event)
    {
        $event['request']->headers->set('Cookie', 'PREF=f6=8');
        $event['request']->headers->set('User-Agent', 'Opera/7.50 (Windows XP; U)');
    }
```
I have tried removing the Cookie line, and nothing changes, but when I remove/change the User-Agent line, I appear to get the new layout, but it will not fully load. Is there something I can change, or is this not fixable? Thanks in advance!

**Comment by kinglyl** [comment]
It seems Youtube does not support old style any more...

**Comment by kinglyl** [comment]
And Youtube in unblockvideos.com is down too

**Comment by kinglyl** [comment]
Aha! I have found the solution and Youtube in my site is working again

**Comment by BinBashBanana** [comment]
What? lmao

**Comment by MapGuy11** [comment]
Its bein worked on here https://github.com/Athlon1600/php-proxy-app/issues/183

**Comment by Athlon1600** [comment]
it seems that youtube permanently retired their old layout, and now there is no way to bring it back.
Youtube has failed to load for a while on php-proxy-app, but now that has been fixed here:
https://github.com/Athlon1600/php-proxy-app/issues/183
