### ISSUE TITLE
Youtube Plugin Doesn't Work

### ISSUE THREAD

**Issue by girimproxy** [Athlon1600/php-proxy-plugin-bundle#7]
Hi,

Youtube plugin seems to not working. Is it just me or youtube changes somethings? When i tried to enter youtube on proxy, I got empty page.

<img width="1277" alt="screen shot 2017-09-11 at 12 44 07" src="https://user-images.githubusercontent.com/30905359/30268642-0ebe8a5c-96ef-11e7-9eaa-b5f7fc7a97c5.png">

**Comment by Athlon1600** [comment]
It should be working now. Just do a "composer update" to get the new plugin version:  
https://github.com/Athlon1600/php-proxy/issues/75#issuecomment-329008313
