### ISSUE TITLE
Xhamster plugin has stopped working

### ISSUE THREAD

**Issue by chronic0383** [Athlon1600/php-proxy-plugin-bundle#9]
I believe they have updated the player, any help would be amazing please.
Oh also thanks for such a great bit of proxy software, do you have anywhere to make donations to help support future builds ?

**Comment by Athlon1600** [comment]
https://github.com/Athlon1600/php-proxy-plugin-bundle/commit/402b9e47870216b780bac76df8941bc2065d8dc3  
  
Should be working now. Try it using the San Francisco server from:  
https://unblockvideos.com/  
  
There is no need for donations. Giving credit to this project is more than enough :)
